services:
  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'
  postgres-auth:
    container_name: postgres-auth
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./api/data/postgres-auth:/data/postgres
    environment:
      - POSTGRES_DB=auth
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  postgres-main:
    container_name: postgres-main
    image: postgres:latest
    ports:
      - "5434:5432"
    volumes:
      - ./api/data/postgres-main:/data/postgres
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  pgadmin:
    links:
      - postgres-main:postgres-main
      - postgres-auth:postgres-auth
    container_name: pgadmin-bowling
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - ./api/data/pgadmin:/root/.pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=super.cool.efrei@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
  bowling_gateway:
    depends_on:
      - rabbitmq
      - bowling-auth
      - bowling-main
    restart: on-failure
    build:
      context: .
      dockerfile: apps/bowling-gateway/Dockerfile
      target: development
    command: pnpm run start:dev bowling-gateway
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  bowling-main:
    depends_on:
      - rabbitmq
      - bowling-auth
      - postgres-main
    restart: on-failure
    build:
      context: .
      dockerfile: ./apps/bowling-main/Dockerfile
      target: development
    command: pnpm run start:dev bowling-main
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  bowling-payment:
    depends_on:
      - rabbitmq
      - bowling-auth
    restart: on-failure
    build:
      context: .
      dockerfile: ./apps/bowling-payment/Dockerfile
      target: development
    command: pnpm run start:dev bowling-payment
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  bowling-auth:
    depends_on:
      - rabbitmq
      - postgres-auth
    restart: on-failure
    build:
      context: .
      dockerfile: ./apps/bowling-auth/Dockerfile
      target: development
    command: pnpm run start:dev bowling-auth
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  mailer:
    depends_on:
      - rabbitmq
    restart: on-failure
    build:
      context: .
      dockerfile: ./apps/bowling-mailer/Dockerfile
      target: development
    command: pnpm run start:dev bowling-mailer
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
