services:
  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'
  bowling_gateway:
    depends_on:
      - rabbitmq
      - bowling-auth
      - bowling-main
    restart: on-failure
    build:
      context: .
      dockerfile: apps/bowling-gateway/Dockerfile
      target: development
    command: pnpm run start:dev bowling-gateway
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  bowling-main:
    depends_on:
      - rabbitmq
      - bowling-auth
    restart: on-failure
    build:
      context: .
      dockerfile: ./apps/bowling-main/Dockerfile
      target: development
    command: pnpm run start:dev bowling-main
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  bowling-auth:
    depends_on:
      - rabbitmq
    restart: on-failure
    build:
      context: .
      dockerfile: ./apps/bowling-auth/Dockerfile
      target: development
    command: pnpm run start:dev bowling-auth
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
