global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
- job_name: 'gateway'
  static_configs:
  - targets: ['localhost:3000']
- job_name: 'auth'
  static_configs:
  - targets: ['localhost:3001']
- job_name: 'main'
  static_configs:
  - targets: ['localhost:3002']